language: java
jdk: openjdk8

before_install:
  - wget http://services.gradle.org/distributions/gradle-6.3-bin.zip
  - unzip -qq gradle-6.3-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.3
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v

script:
  - ./dev war
  - ./dev test

after_success:
  - bash <(curl -s https://codecov.io/bash)
